---
title: API Reference
weight: 2
---

<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# observe

```go
import "github.com/danmestas/dagnats/observe"
```

## Index

- [func ContextWithParentInfo\(ctx context.Context, traceID, spanID string\) context.Context](<#ContextWithParentInfo>)
- [type Attribute](<#Attribute>)
  - [func BoolAttr\(key string, val bool\) Attribute](<#BoolAttr>)
  - [func Float64Attr\(key string, val float64\) Attribute](<#Float64Attr>)
  - [func Int64Attr\(key string, val int64\) Attribute](<#Int64Attr>)
  - [func StringAttr\(key, val string\) Attribute](<#StringAttr>)
- [type Counter](<#Counter>)
- [type ErrorReporter](<#ErrorReporter>)
  - [func NewNoopErrorReporter\(\) ErrorReporter](<#NewNoopErrorReporter>)
- [type Field](<#Field>)
  - [func Err\(err error\) Field](<#Err>)
  - [func Int\(key string, val int\) Field](<#Int>)
  - [func String\(key, val string\) Field](<#String>)
- [type Gauge](<#Gauge>)
- [type Histogram](<#Histogram>)
- [type Level](<#Level>)
  - [func \(l Level\) String\(\) string](<#Level.String>)
- [type Logger](<#Logger>)
  - [func NewNoopLogger\(\) Logger](<#NewNoopLogger>)
- [type Metrics](<#Metrics>)
  - [func NewNoopMetrics\(\) Metrics](<#NewNoopMetrics>)
- [type ParentInfo](<#ParentInfo>)
  - [func ParentInfoFromContext\(ctx context.Context\) \(ParentInfo, bool\)](<#ParentInfoFromContext>)
- [type Span](<#Span>)
- [type SpanContext](<#SpanContext>)
- [type SpanKind](<#SpanKind>)
- [type SpanOption](<#SpanOption>)
  - [func WithAttributes\(attrs ...Attribute\) SpanOption](<#WithAttributes>)
  - [func WithSpanKind\(kind SpanKind\) SpanOption](<#WithSpanKind>)
- [type StatusCode](<#StatusCode>)
- [type Telemetry](<#Telemetry>)
  - [func NewNoopTelemetry\(\) \*Telemetry](<#NewNoopTelemetry>)
- [type Tracer](<#Tracer>)
  - [func NewNoopTracer\(\) Tracer](<#NewNoopTracer>)


<a name="ContextWithParentInfo"></a>
## func ContextWithParentInfo

```go
func ContextWithParentInfo(ctx context.Context, traceID, spanID string) context.Context
```

ContextWithParentInfo stores remote parent span info in ctx. Used by propagation code to pass trace context from incoming NATS messages to Tracer.Start without importing vendor packages.

<a name="Attribute"></a>
## type Attribute

Attribute is a typed key\-value pair attached to spans and events. Value must be one of: string, int64, float64, bool — adapters may panic on other types to surface programmer errors early.

```go
type Attribute struct {
    Key   string
    Value any
}
```

<a name="BoolAttr"></a>
### func BoolAttr

```go
func BoolAttr(key string, val bool) Attribute
```

BoolAttr constructs an Attribute with a bool value.

<a name="Float64Attr"></a>
### func Float64Attr

```go
func Float64Attr(key string, val float64) Attribute
```

Float64Attr constructs an Attribute with a float64 value.

<a name="Int64Attr"></a>
### func Int64Attr

```go
func Int64Attr(key string, val int64) Attribute
```

Int64Attr constructs an Attribute with an int64 value.

<a name="StringAttr"></a>
### func StringAttr

```go
func StringAttr(key, val string) Attribute
```

StringAttr constructs an Attribute with a string value.

<a name="Counter"></a>
## type Counter

Counter is a monotonically increasing metric instrument.

```go
type Counter interface {
    Inc()
    Add(delta float64)
}
```

<a name="ErrorReporter"></a>
## type ErrorReporter

ErrorReporter captures exceptions and messages to an external error\-tracking backend. The concrete backend \(e.g. Sentry\) lives in a separate adapter package; this interface keeps engine/worker/api independent of any vendor import.

```go
type ErrorReporter interface {
    CaptureError(ctx context.Context, err error, tags map[string]string)
    CaptureMessage(ctx context.Context, msg string, level Level)
}
```

<a name="NewNoopErrorReporter"></a>
### func NewNoopErrorReporter

```go
func NewNoopErrorReporter() ErrorReporter
```

NewNoopErrorReporter returns an ErrorReporter that discards all captures.

<a name="Field"></a>
## type Field

Field is a typed key\-value pair for structured log and error report context.

```go
type Field struct {
    Key   string
    Value any
}
```

<a name="Err"></a>
### func Err

```go
func Err(err error) Field
```

Err constructs a Field that captures an error under the conventional "error" key.

<a name="Int"></a>
### func Int

```go
func Int(key string, val int) Field
```

Int constructs a Field with an int value.

<a name="String"></a>
### func String

```go
func String(key, val string) Field
```

String constructs a Field with a string value.

<a name="Gauge"></a>
## type Gauge

Gauge is a metric that can go up or down \(e.g. queue depth, active goroutines\).

```go
type Gauge interface {
    Set(value float64)
    Inc()
    Dec()
}
```

<a name="Histogram"></a>
## type Histogram

Histogram records observations in configurable buckets \(e.g. latency, payload size\).

```go
type Histogram interface {
    Observe(value float64)
}
```

<a name="Level"></a>
## type Level

Level represents the severity of an observability event. Ordered from least to most severe; only values in levelStrings are valid.

```go
type Level int
```

<a name="LevelDebug"></a>

```go
const (
    LevelDebug Level = iota
    LevelInfo
    LevelWarn
    LevelError
)
```

<a name="Level.String"></a>
### func \(Level\) String

```go
func (l Level) String() string
```

String returns the lowercase name of the level. Panics on unknown levels to surface programmer errors at the call site rather than silently corrupting output.

<a name="Logger"></a>
## type Logger

Logger is the structured logging contract. Implementations must be safe for concurrent use. With returns a new Logger that prepends the given fields to every subsequent log call — it must never return nil.

```go
type Logger interface {
    Info(msg string, fields ...Field)
    Error(msg string, err error, fields ...Field)
    With(fields ...Field) Logger
}
```

<a name="NewNoopLogger"></a>
### func NewNoopLogger

```go
func NewNoopLogger() Logger
```

NewNoopLogger returns a Logger that discards all output.

<a name="Metrics"></a>
## type Metrics

Metrics is the factory for named metric instruments. Tags are label key\-value pairs that the underlying backend attaches to each observation. The concrete backend \(e.g. Prometheus, OTel\) lives in a separate adapter package.

```go
type Metrics interface {
    Counter(name string, tags map[string]string) Counter
    Histogram(name string, tags map[string]string) Histogram
    Gauge(name string, tags map[string]string) Gauge
}
```

<a name="NewNoopMetrics"></a>
### func NewNoopMetrics

```go
func NewNoopMetrics() Metrics
```

NewNoopMetrics returns a Metrics factory that produces no\-op instruments.

<a name="ParentInfo"></a>
## type ParentInfo

ParentInfo carries trace/span IDs from an extracted traceparent so that Tracer.Start implementations can link child spans to remote parents across process/message boundaries.

```go
type ParentInfo struct {
    TraceID string
    SpanID  string
}
```

<a name="ParentInfoFromContext"></a>
### func ParentInfoFromContext

```go
func ParentInfoFromContext(ctx context.Context) (ParentInfo, bool)
```

ParentInfoFromContext returns any ParentInfo stored in ctx. Returns ok=false when no parent info is present.

<a name="Span"></a>
## type Span

Span represents a single unit of work in a distributed trace. End must be called exactly once; all other methods are safe to call in any order before End.

```go
type Span interface {
    End()
    SetStatus(code StatusCode, description string)
    SetAttributes(attrs ...Attribute)
    RecordError(err error)
    AddEvent(name string, attrs ...Attribute)
}
```

<a name="SpanContext"></a>
## type SpanContext

SpanContext exposes trace/span IDs for cross\-process propagation. Span implementations may optionally implement this interface. Callers use type assertion: if sc, ok := span.\(SpanContext\); ok \{ ... \}

```go
type SpanContext interface {
    TraceID() string
    SpanID() string
}
```

<a name="SpanKind"></a>
## type SpanKind

SpanKind describes the role a span plays in a distributed trace. Internal is the safe default; Server/Client distinguish RPC boundaries.

```go
type SpanKind int
```

<a name="SpanKindInternal"></a>

```go
const (
    SpanKindInternal SpanKind = iota
    SpanKindServer   SpanKind = iota
    SpanKindClient   SpanKind = iota
)
```

<a name="SpanOption"></a>
## type SpanOption

SpanOption is a sealed option type for Tracer.Start. The private marker method prevents external packages from implementing the interface, keeping the option set under our control while remaining extensible within observe.

```go
type SpanOption interface {
    // contains filtered or unexported methods
}
```

<a name="WithAttributes"></a>
### func WithAttributes

```go
func WithAttributes(attrs ...Attribute) SpanOption
```

WithAttributes attaches Attributes to the span at creation time.

<a name="WithSpanKind"></a>
### func WithSpanKind

```go
func WithSpanKind(kind SpanKind) SpanOption
```

WithSpanKind sets the kind of the span being started.

<a name="StatusCode"></a>
## type StatusCode

StatusCode classifies the outcome of a span. Only StatusOK and StatusError are valid; callers that pass unknown values will encounter panics in adapters.

```go
type StatusCode int
```

<a name="StatusOK"></a>

```go
const (
    StatusOK    StatusCode = iota
    StatusError StatusCode = iota
)
```

<a name="Telemetry"></a>
## type Telemetry

Telemetry bundles all observability interfaces. Passed as a single argument to component constructors instead of separate parameters. All fields must be non\-nil — use Noop constructors for safe defaults.

```go
type Telemetry struct {
    Tracer  Tracer
    Logger  Logger
    Metrics Metrics
    Errors  ErrorReporter
}
```

<a name="NewNoopTelemetry"></a>
### func NewNoopTelemetry

```go
func NewNoopTelemetry() *Telemetry
```

NewNoopTelemetry returns a Telemetry with all noop implementations. Safe default for tests and environments where telemetry is not needed.

<a name="Tracer"></a>
## type Tracer

Tracer creates Spans. Implementations must be safe for concurrent use. The returned context carries the new span so downstream calls can propagate it.

```go
type Tracer interface {
    Start(ctx context.Context, name string, opts ...SpanOption) (context.Context, Span)
}
```

<a name="NewNoopTracer"></a>
### func NewNoopTracer

```go
func NewNoopTracer() Tracer
```

NewNoopTracer returns a Tracer that produces no\-op spans and discards all data.

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
