---
title: API Reference
weight: 2
---

<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# protocol

```go
import "github.com/danmestas/dagnats/protocol"
```

## Index

- [type Event](<#Event>)
  - [func NewStepEvent\(eventType EventType, runID string, stepID string, payload \[\]byte\) Event](<#NewStepEvent>)
  - [func NewWorkflowEvent\(eventType EventType, runID string, payload \[\]byte\) Event](<#NewWorkflowEvent>)
  - [func UnmarshalEvent\(data \[\]byte\) \(Event, error\)](<#UnmarshalEvent>)
  - [func \(e Event\) Marshal\(\) \(\[\]byte, error\)](<#Event.Marshal>)
  - [func \(e Event\) NATSMsgID\(\) string](<#Event.NATSMsgID>)
  - [func \(e Event\) NATSSubject\(\) string](<#Event.NATSSubject>)
- [type EventType](<#EventType>)
- [type FailureType](<#FailureType>)
- [type StepFailedPayload](<#StepFailedPayload>)
- [type TaskPayload](<#TaskPayload>)
- [type TaskResolution](<#TaskResolution>)


<a name="Event"></a>
## type Event

Event is the core communication primitive published to the history stream. Payload carries event\-specific data as raw JSON to keep the type schema\-agnostic.

```go
type Event struct {
    Type        EventType       `json:"type"`
    RunID       string          `json:"run_id"`
    StepID      string          `json:"step_id,omitempty"`
    Timestamp   time.Time       `json:"timestamp"`
    Payload     json.RawMessage `json:"payload,omitempty"`
    TraceParent string          `json:"trace_parent,omitempty"`
    TraceState  string          `json:"trace_state,omitempty"`
    WorkerID    string          `json:"worker_id,omitempty"`
}
```

<a name="NewStepEvent"></a>
### func NewStepEvent

```go
func NewStepEvent(eventType EventType, runID string, stepID string, payload []byte) Event
```

NewStepEvent constructs an Event for a step lifecycle transition. Panics on empty runID or stepID — these are programmer errors, not runtime errors.

<a name="NewWorkflowEvent"></a>
### func NewWorkflowEvent

```go
func NewWorkflowEvent(eventType EventType, runID string, payload []byte) Event
```

NewWorkflowEvent constructs an Event for a workflow lifecycle transition. Panics on empty runID — programmer error.

<a name="UnmarshalEvent"></a>
### func UnmarshalEvent

```go
func UnmarshalEvent(data []byte) (Event, error)
```

UnmarshalEvent deserializes a NATS message body into an Event.

<a name="Event.Marshal"></a>
### func \(Event\) Marshal

```go
func (e Event) Marshal() ([]byte, error)
```

Marshal serializes the event to JSON for publishing to NATS.

<a name="Event.NATSMsgID"></a>
### func \(Event\) NATSMsgID

```go
func (e Event) NATSMsgID() string
```

NATSMsgID returns the deduplication ID for JetStream idempotent publishing. Composed of run, step, and event type so replays are safe. For workflow events \(empty StepID\), omits the step segment to avoid double dots.

<a name="Event.NATSSubject"></a>
### func \(Event\) NATSSubject

```go
func (e Event) NATSSubject() string
```

NATSSubject returns the JetStream subject for publishing this event. All events for a run share one subject so consumers get ordered history. Panics on empty RunID — subjects with empty segments are invalid in NATS.

<a name="EventType"></a>
## type EventType

EventType identifies the kind of workflow lifecycle event. Using string constants makes events self\-describing over the wire.

```go
type EventType string
```

<a name="EventWorkflowStarted"></a>

```go
const (
    EventWorkflowStarted          EventType = "workflow.started"
    EventStepQueued               EventType = "step.queued"
    EventStepStarted              EventType = "step.started"
    EventStepCompleted            EventType = "step.completed"
    EventStepFailed               EventType = "step.failed"
    EventStepContinue             EventType = "step.continue"
    EventAgentLoopIteration       EventType = "agent.loop.iteration"
    EventStepMapStarted           EventType = "step.map.started"
    EventStepMapCompleted         EventType = "step.map.completed"
    EventStepMapInstanceCompleted EventType = "step.map.instance.completed"
    EventStepSleepStarted         EventType = "step.sleep.started"
    EventStepSleepCompleted       EventType = "step.sleep.completed"
    EventStepWaitStarted          EventType = "step.wait.started"
    EventStepWaitMatched          EventType = "step.wait.matched"
    EventStepWaitTimeout          EventType = "step.wait.timeout"
    EventWorkflowCompleted        EventType = "workflow.completed"
    EventWorkflowFailed           EventType = "workflow.failed"
    EventWorkflowSpawn            EventType = "workflow.spawn"
    EventWorkflowChildCompleted   EventType = "workflow.child.completed"
    EventWorkflowChildFailed      EventType = "workflow.child.failed"
    EventWorkflowCancelled        EventType = "workflow.cancelled"
    EventStepCancelled            EventType = "step.cancelled"
    EventCompensateStarted        EventType = "compensate.started"
    EventCompensateStepCompleted  EventType = "compensate.step.completed"
    EventCompensateFailed         EventType = "compensate.failed"
    EventCompensateCompleted      EventType = "compensate.completed"
    EventApprovalRequested        EventType = "approval.requested"
    EventApprovalGranted          EventType = "approval.granted"
    EventApprovalRejected         EventType = "approval.rejected"
    EventApprovalExpired          EventType = "approval.expired"
    EventPlannerMaterialized      EventType = "planner.materialized"
)
```

<a name="FailureType"></a>
## type FailureType

FailureType distinguishes how the engine handles a step failure.

```go
type FailureType string
```

<a name="FailureTypeRetriable"></a>

```go
const (
    FailureTypeRetriable    FailureType = "retriable"
    FailureTypeNonRetriable FailureType = "non_retriable"
    FailureTypeRetryAfter   FailureType = "retry_after"
)
```

<a name="StepFailedPayload"></a>
## type StepFailedPayload

StepFailedPayload is the structured payload for EventStepFailed. FailureType defaults to retriable when empty \(backward compat\). RetryAfterMs is only used with FailureTypeRetryAfter.

```go
type StepFailedPayload struct {
    Error        string      `json:"error"`
    FailureType  FailureType `json:"failure_type,omitempty"`
    RetryAfterMs int64       `json:"retry_after_ms,omitempty"`
}
```

<a name="TaskPayload"></a>
## type TaskPayload

TaskPayload is the message body published to a task subject when the engine dispatches a step for execution. Workers unmarshal this to build a TaskContext. Iteration is the agent\-loop iteration index \(0 for the first execution\); workers include it in Continue event MsgIds to prevent JetStream deduplication across cycles.

```go
type TaskPayload struct {
    TaskID    string          `json:"task_id"` // {runID}.{stepID}
    RunID     string          `json:"run_id"`
    StepID    string          `json:"step_id"`
    Iteration int             `json:"iteration,omitempty"`
    Attempt   int             `json:"attempt,omitempty"`
    Input     json.RawMessage `json:"input,omitempty"`
}
```

<a name="TaskResolution"></a>
## type TaskResolution

TaskResolution is the wire format for HTTP bridge resolve actions. The action field discriminates between complete/fail/pause/checkpoint. Workers POST this to /v1/tasks/\{id\}/resolve to report task outcomes.

```go
type TaskResolution struct {
    Action     string          `json:"action"`
    Output     json.RawMessage `json:"output,omitempty"`
    Error      string          `json:"error,omitempty"`
    Name       string          `json:"name,omitempty"`
    DurationMs int64           `json:"duration_ms,omitempty"`
    Checkpoint json.RawMessage `json:"checkpoint,omitempty"`
    Data       json.RawMessage `json:"data,omitempty"`
}
```

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
