---
title: API Reference
weight: 2
---

<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# dagnatstest

```go
import "github.com/danmestas/dagnats/dagnatstest"
```

Package dagnatstest provides test helpers for DagNats workflows. It starts an embedded NATS server with all required streams and KV buckets in a single call, ready for workflow testing.

Usage:

```
func TestMyWorkflow(t *testing.T) {
    nc := dagnatstest.Server(t)
    // nc is ready — register workflows, start workers, etc.
}
```

## Index

- [func Server\(t \*testing.T\) \*nats.Conn](<#Server>)


<a name="Server"></a>
## func Server

```go
func Server(t *testing.T) *nats.Conn
```

Server starts an embedded NATS server with JetStream and all required streams/KV buckets provisioned. Returns the connected client. Server and connection are cleaned up automatically when the test ends.

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
