---
title: API Reference
weight: 2
---

<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# actor

```go
import "github.com/danmestas/dagnats/actor"
```

actor/actor.go The actor package provides a lightweight actor runtime for DagNats. Actors are goroutines with channel mailboxes, supervised by parent actors. Pure Go — no NATS imports. NATS integration lives in engine/.

## Index

- [Variables](<#variables>)
- [type Actor](<#Actor>)
- [type Address](<#Address>)
  - [func \(a Address\) String\(\) string](<#Address.String>)
- [type AllForOne](<#AllForOne>)
  - [func \(s \*AllForOne\) Decide\(err error\) Directive](<#AllForOne.Decide>)
  - [func \(s \*AllForOne\) RestartScope\(\) RestartScope](<#AllForOne.RestartScope>)
- [type Context](<#Context>)
  - [func \(c \*Context\) Self\(\) Address](<#Context.Self>)
  - [func \(c \*Context\) Send\(to Address, payload any\) error](<#Context.Send>)
  - [func \(c \*Context\) Spawn\(addr Address, actor Actor, opts ...SpawnOption\) error](<#Context.Spawn>)
- [type Directive](<#Directive>)
  - [func \(d Directive\) String\(\) string](<#Directive.String>)
- [type Lifecycle](<#Lifecycle>)
- [type Message](<#Message>)
- [type OneForOne](<#OneForOne>)
  - [func \(s \*OneForOne\) Decide\(err error\) Directive](<#OneForOne.Decide>)
  - [func \(s \*OneForOne\) RestartScope\(\) RestartScope](<#OneForOne.RestartScope>)
- [type RestartScope](<#RestartScope>)
- [type RestartTracker](<#RestartTracker>)
  - [func NewRestartTracker\(limit int, window time.Duration\) \*RestartTracker](<#NewRestartTracker>)
  - [func \(tr \*RestartTracker\) Allow\(\) bool](<#RestartTracker.Allow>)
- [type Runtime](<#Runtime>)
  - [func NewRuntime\(\) \*Runtime](<#NewRuntime>)
  - [func \(r \*Runtime\) Send\(to Address, msg Message\) error](<#Runtime.Send>)
  - [func \(r \*Runtime\) Spawn\(addr Address, actor Actor, opts ...SpawnOption\) error](<#Runtime.Spawn>)
  - [func \(r \*Runtime\) Stop\(addr Address\) error](<#Runtime.Stop>)
  - [func \(r \*Runtime\) StopAll\(\)](<#Runtime.StopAll>)
- [type SpawnOption](<#SpawnOption>)
  - [func WithMailboxSize\(size int\) SpawnOption](<#WithMailboxSize>)
  - [func WithSupervision\(s SupervisionStrategy\) SpawnOption](<#WithSupervision>)
- [type SupervisionStrategy](<#SupervisionStrategy>)


## Variables

<a name="ErrActorNotFound"></a>ErrActorNotFound is returned when sending to an unknown address.

```go
var ErrActorNotFound = fmt.Errorf("actor: not found")
```

<a name="ErrAlreadyExists"></a>ErrAlreadyExists is returned when spawning at an occupied address.

```go
var ErrAlreadyExists = fmt.Errorf("actor: already exists")
```

<a name="ErrMailboxFull"></a>ErrMailboxFull is returned when an actor's mailbox is at capacity.

```go
var ErrMailboxFull = fmt.Errorf("actor: mailbox full")
```

<a name="Actor"></a>
## type Actor

Actor is the interface all actors implement. Receive processes one message at a time — the runtime guarantees sequential delivery.

```go
type Actor interface {
    // Receive processes a single message. Returning an error
    // triggers the supervision strategy.
    Receive(ctx *Context, msg Message) error
}
```

<a name="Address"></a>
## type Address

Address uniquely identifies an actor within the runtime.

```go
type Address struct {
    Type string // e.g. "workflow", "worker", "tool"
    ID   string // e.g. run ID, worker ID
}
```

<a name="Address.String"></a>
### func \(Address\) String

```go
func (a Address) String() string
```

String formats the address as "type.id" for logging and map keys.

<a name="AllForOne"></a>
## type AllForOne

AllForOne restarts all siblings when any child fails. Useful when children have interdependent state.

```go
type AllForOne struct {
    // Decider maps errors to directives. If nil, defaults to Restart.
    Decider func(error) Directive
}
```

<a name="AllForOne.Decide"></a>
### func \(\*AllForOne\) Decide

```go
func (s *AllForOne) Decide(err error) Directive
```

Decide returns the directive for the given error.

<a name="AllForOne.RestartScope"></a>
### func \(\*AllForOne\) RestartScope

```go
func (s *AllForOne) RestartScope() RestartScope
```

RestartScope returns RestartAll — all siblings restart.

<a name="Context"></a>
## type Context

Context provides services to a running actor.

```go
type Context struct {
    // contains filtered or unexported fields
}
```

<a name="Context.Self"></a>
### func \(\*Context\) Self

```go
func (c *Context) Self() Address
```

Self returns this actor's address.

<a name="Context.Send"></a>
### func \(\*Context\) Send

```go
func (c *Context) Send(to Address, payload any) error
```

Send delivers a message to another actor's mailbox. Returns an error if the target actor is not found or its mailbox is full.

<a name="Context.Spawn"></a>
### func \(\*Context\) Spawn

```go
func (c *Context) Spawn(addr Address, actor Actor, opts ...SpawnOption) error
```

Spawn creates a child actor supervised by this actor.

<a name="Directive"></a>
## type Directive

Directive tells a supervisor how to handle a failed child.

```go
type Directive int
```

<a name="Restart"></a>

```go
const (
    Restart  Directive = iota // Restart the failed actor
    Stop                      // Stop the actor permanently
    Escalate                  // Escalate failure to parent
    Resume                    // Ignore the error, continue
)
```

<a name="Directive.String"></a>
### func \(Directive\) String

```go
func (d Directive) String() string
```

String returns the lowercase name of the directive.

<a name="Lifecycle"></a>
## type Lifecycle

Lifecycle extends Actor with optional startup/shutdown hooks. Actors that don't need hooks can implement Actor alone.

```go
type Lifecycle interface {
    // PreStart runs before the actor begins receiving messages.
    // Errors here trigger supervision (the actor never starts).
    PreStart(ctx *Context) error

    // PostStop runs after the actor stops receiving messages.
    // Used for cleanup. Errors are logged but not supervised.
    PostStop(ctx *Context)
}
```

<a name="Message"></a>
## type Message

Message is the envelope delivered to an actor's mailbox.

```go
type Message struct {
    From    Address
    Payload any
}
```

<a name="OneForOne"></a>
## type OneForOne

OneForOne restarts only the failed child. The default strategy.

```go
type OneForOne struct {
    // Decider maps errors to directives. If nil, defaults to Restart.
    Decider func(error) Directive
}
```

<a name="OneForOne.Decide"></a>
### func \(\*OneForOne\) Decide

```go
func (s *OneForOne) Decide(err error) Directive
```

Decide returns the directive for the given error.

<a name="OneForOne.RestartScope"></a>
### func \(\*OneForOne\) RestartScope

```go
func (s *OneForOne) RestartScope() RestartScope
```

RestartScope returns RestartOne — only the failed child restarts.

<a name="RestartScope"></a>
## type RestartScope

RestartScope controls which actors restart on a failure.

```go
type RestartScope int
```

<a name="RestartOne"></a>

```go
const (
    RestartOne RestartScope = iota // Only the failed actor
    RestartAll                     // All children of the supervisor
)
```

<a name="RestartTracker"></a>
## type RestartTracker

RestartTracker enforces a bounded number of restarts within a sliding time window. If the limit is exceeded, the tracker signals that the actor should be stopped or escalated.

```go
type RestartTracker struct {
    // contains filtered or unexported fields
}
```

<a name="NewRestartTracker"></a>
### func NewRestartTracker

```go
func NewRestartTracker(limit int, window time.Duration) *RestartTracker
```

NewRestartTracker creates a tracker allowing limit restarts within the given window. Panics if limit \< 1.

<a name="RestartTracker.Allow"></a>
### func \(\*RestartTracker\) Allow

```go
func (tr *RestartTracker) Allow() bool
```

Allow returns true if a restart is permitted. It prunes expired entries, then checks the count against the limit. If allowed, it records the restart time.

<a name="Runtime"></a>
## type Runtime

Runtime manages actor lifecycle, message delivery, and supervision. All methods are safe for concurrent use.

```go
type Runtime struct {
    // contains filtered or unexported fields
}
```

<a name="NewRuntime"></a>
### func NewRuntime

```go
func NewRuntime() *Runtime
```

NewRuntime creates an empty actor runtime.

<a name="Runtime.Send"></a>
### func \(\*Runtime\) Send

```go
func (r *Runtime) Send(to Address, msg Message) error
```

Send delivers a message to an actor's mailbox. Returns ErrActorNotFound if the address is unknown, ErrMailboxFull if the channel is at capacity.

<a name="Runtime.Spawn"></a>
### func \(\*Runtime\) Spawn

```go
func (r *Runtime) Spawn(addr Address, actor Actor, opts ...SpawnOption) error
```

Spawn starts a new root\-level actor. Use Context.Spawn for supervised child actors. Returns ErrAlreadyExists if the address is taken.

<a name="Runtime.Stop"></a>
### func \(\*Runtime\) Stop

```go
func (r *Runtime) Stop(addr Address) error
```

Stop gracefully terminates an actor and its children.

<a name="Runtime.StopAll"></a>
### func \(\*Runtime\) StopAll

```go
func (r *Runtime) StopAll()
```

StopAll terminates all actors. Used in defer for cleanup.

<a name="SpawnOption"></a>
## type SpawnOption

SpawnOption configures actor spawning.

```go
type SpawnOption func(*spawnOptions)
```

<a name="WithMailboxSize"></a>
### func WithMailboxSize

```go
func WithMailboxSize(size int) SpawnOption
```

WithMailboxSize sets the buffered channel capacity.

<a name="WithSupervision"></a>
### func WithSupervision

```go
func WithSupervision(s SupervisionStrategy) SpawnOption
```

WithSupervision sets the strategy for this actor's children.

<a name="SupervisionStrategy"></a>
## type SupervisionStrategy

SupervisionStrategy decides how to handle a failed child actor. The runtime calls Decide when an actor's Receive returns an error.

```go
type SupervisionStrategy interface {
    // Decide returns the directive for handling the failure.
    Decide(err error) Directive

    // RestartScope controls whether a failure restarts one child
    // or all siblings under the same supervisor.
    RestartScope() RestartScope
}
```

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
